version: "3.9"

services:

  app:
    build: .
    volumes:
      - .:/root
    depends_on:
      - database
    links:
      - database

  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'exercises'
      MYSQL_USER: 'dbuser'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
